### PR TITLE
contract deploy on multiple testnet

### PR DESCRIPTION
**Pull request by ganesh1233456**
hey @wottpal I found [chain.ts](https://github.com/scio-labs/use-inkathon/blob/main/src/chains.ts) link where substrate chain are define. I manage to change chain network by changing [here](https://github.com/scio-labs/inkathon/blob/5d54afa3a64d6f9c0d561299ed777ebbf4393b94/packages/frontend/.env.local.example#L23) and added  multiple network `NEXT_PUBLIC_SUPPORTED_CHAINS=["alephzero-testnet","shibuya"]` this way in .env.local file. I use deployed contract address in different network in this way.
```
{
  "address_alpha_zero": "5GEPzw52kYZ3fX4kCFZReZzVeYQ5U8eehYUEsg12JdFSL44t",
  "address_shibuya": "abQXX6bdJVy1H8mJHEhmEhVDakjFdMPU6Lu5VN4eTvp3eSQ"
}
```

I try to run the project with `pnpm dev` but contract interaction section is hidden.

Screenshot 2023-02-19 at 09 29 22

I think this is because of null contract as define in [here](https://github.com/scio-labs/inkathon/blob/5d54afa3a64d6f9c0d561299ed777ebbf4393b94/packages/frontend/src/components/web3/GreeterContractInteractions.tsx#L68) but [here](https://github.com/scio-labs/inkathon/blob/5d54afa3a64d6f9c0d561299ed777ebbf4393b94/packages/frontend/src/components/web3/GreeterContractInteractions.tsx#L17) contract greeting is used in `useRegisteredContract `. I wonder what I am doing wrong using multiple testnet?

### CODE REVIEW

**Comment by wottpal** [comment]
Hey, two things:

* I know right now there is a bug that hides contracts after chain switching when multiple chains are defined. So I recommend you go with `shibuya`-only for now (should have this fixed by end of this week):
```
NEXT_PUBLIC_DEFAULT_CHAIN=shibuya
NEXT_PUBLIC_SUPPORTED_CHAINS=["shibuya"]
```

* Second, I recommend using one address file per chain, like `deployments/{contract}/shibuya.json`, which only exports one address. This way makes it easy to e.g. gitignore certain chains (i.e. `development`). **Teaser**: I'm very close to finish completely new deploy CLI scripts (that deploy & write those address files all in one command automatically).

**Comment by ganesh1233456** [comment]
@wottpal thanks for Kind reply🤗. We are Eagerly waiting for this merge. BTW I manage to configure shibuya as per your say and contract display but no data fetch and can't  possible to add data. I think right now it only work for `alephzeroTestnet`. Am I right?
Screenshot 2023-02-20 at 08 01 13

**Comment by wottpal** [comment]
Hey @ganesh1233456, some **updates** already:

* I updated `use-inkathon` to https://github.com/scio-labs/use-inkathon/releases/tag/0.0.1-alpha.21 incl. some breaking changes proposed by your friend. But also to be better compatible with shibuya (updated network definitions & balance formatting to support shibuya).
* I already added the new build & deployment mechanism teased above to the `contracts` package. It isn't fully documented yet, sorry for that. Breaking change: Address files are `deployments/{contract}/{network}.ts` files with one single export line and **no `.json` anymore**.
* I created a new branch `shibuya-test` where I've created a sample shibuya deployment & updated deployment imports ([see the diff](https://github.com/scio-labs/inkathon/compare/main...scio-labs:inkathon:shibuya-test)). I also created a little sample deployment that you can verify it's working: https://inkathon-shibuya.vercel.app/.

My To-Dos from here:
* Fix multichain contract handling in `use-inkathon` (https://github.com/scio-labs/use-inkathon/issues/12)
* Update `inkathon` docs on new deployment scripts

I also just created a Telegram group for ink!athon developers, please join :) 
https://t.me/inkathon

**Comment by wottpal** [comment]
And one last thing: I didn't know how slow Shibuya/Astar is. So the success notification currently is way to fast and you have to wait ~10+ seconds for the greeting to update. Have you ever tried Aleph Zero with sub-second blocktime & finality? 🤓

**Comment by nicolad** [comment]
> And one last thing: I didn't know how slow Shibuya/Astar is. So the success notification currently is way to fast and you have to wait ~10+ seconds for the greeting to update. Have you ever tried Aleph Zero with sub-second blocktime & finality? 🤓

I think this is really important for the end dApp, because we don't want consumers of the app to wait on the FE.

**Comment by wottpal** [comment]
> I think this is really important for the end dApp, because we don't want consumers of the app to wait on the FE.

Btw I didn't mention. When I've fixed the multichain thing and integrated shibuya in the official inkathon.xyz deployment, I'll also add a loading animation and only show the success animation when the greeting really has changed ;)

**Comment by ganesh1233456** [comment]
@wottpal sorry to bother you but I am having issue here I don't know why?
From [here](https://github.com/scio-labs/inkathon#contracts-quickstart)
```
# Copy the deployed contracts address and save it via the following command
ADDRESS=… pnpm write-address

# NOTE: This command can also be adapted for different contracts and chains
ADDRESS=123 CHAIN=alephzero-testnet CONTRACT=new_greeter pnpm write-address
```
I am using these command to copy the deployed contract address and second one. I am confused here.
for 1st one, I tried all this below command but they all throws error. How exactly should we suppose to use those command to save contract address? and `...` why this? Why this are not working? What am I doing wrong? 

```
ADDRESS=… pnpm 5DvRByPNvtxkbU1v9EbzeEe9gfgw5wd5SRX6oz
ADDRESS=pnpm 5DvRByPNvtxkbU1v9EbzeEe9gfgw5wd5SRX6ozNxKPgsgSSH
pnpm 5DvRByPNvtxkbU1v9EbzeEe9gfgw5wd5SRX6ozNxKPgsgSSH
```

**Comment by wottpal** [comment]
No worries, as I said I changed the deployment & address export here:

> I already added the new build & deployment mechanism teased above to the contracts package. It isn't fully documented yet, sorry for that. Breaking change: Address files are deployments/{contract}/{network}.ts files with one single export line and no .json anymore.

So instead of using `pnpm build` & `pnpm address-export`, try `./build-all.sh`. Actually, I'll update the package.json scripts now to prevent further confusion.

**Comment by wottpal** [comment]
Just updated [README](https://github.com/scio-labs/inkathon/#contracts-quickstart) & the [`contracts/package.json`](https://github.com/scio-labs/inkathon/blob/main/packages/contracts/package.json#L6) scripts ;) Hope that helps!

**Comment by ganesh1233456** [comment]
> Just updated [README](https://github.com/scio-labs/inkathon/#contracts-quickstart) & the [`contracts/package.json`](https://github.com/scio-labs/inkathon/blob/main/packages/contracts/package.json#L6) scripts ;) Hope that helps!

hey @wottpal it helps but I have still one confusion what if I wan't to build multiple contract? I added contract with ("", "") & ["", ""] and I change Cargo.toml workspace like this:

```
[workspace]

members = [
    "flipper", "greeter"
]
```
but can't possible to build multiple contract at a same time.  I wonder is building multiple contract at same time make sense? If so then how it is possible here?

Screenshot 2023-02-20 at 18 35 55

**Comment by wottpal** [comment]
Define multiple contracts in `build-all.sh` without comma, like:

```bash
contracts=( "flipper" "greeter" )
```

It's a dumb bash convention just to use spaces..

**Comment by ganesh1233456** [comment]
> Define multiple contracts in `build-all.sh` without comma, like:
> 
> ```shell
> contracts=( "flipper" "greeter" )
> ```
> 
> It's a dumb bash convention just to use spaces..

thanks work fine

**Pull request closed without merging**
