### PR TITLE
feat: Migrate to next js app dir, vanilla tailwind and shadcn/ui

### LINKED ISSUE #21: Migrate to Next.js 13 app directory
Migrate the current pages directory to the Next.js 13 app directory/router (https://nextjs.org/docs/app).

### PR DESCRIPTION
**Pull request by ical10**
Closes #21 and #22

### CODE REVIEW

**Review by wottpal — CHANGES_REQUESTED** [review]
Very good progress, @ical10! 🚀

FYI, I also added a few changes & did some refactorings!

Unfortunately, there have been some little misunderstandings regarding #22 which caused you quite some extra work, I guess. I wanted to keep the styling as plain & simple as possible and don't rebuild everything exactly like it looked with chakra-ui. 🤔 Just for simplicity and as-less-as-possible extra code. Also, I wanted to keep the `src/components/ui` shadcn-only and necessary changes as little as possible to the "root" components (so they stay updatable). Wdyt about this? I'm also unsure now as you did all the styling already whether to keep it...

**Comment by ical10** [comment]
> Very good progress, @ical10! 🚀
> 
> FYI, I also added a few changes & did some refactorings!
> 
> Unfortunately, there have been some little misunderstandings regarding #22 which caused you quite some extra work, I guess. I wanted to keep the styling as plain & simple as possible and don't rebuild everything exactly like it looked with chakra-ui. 🤔 Just for simplicity and as-less-as-possible extra code. Also, I wanted to keep the `src/components/ui` shadcn-only and necessary changes as little as possible to the "root" components (so they stay updatable). Wdyt about this? I'm also unsure now as you did all the styling already whether to keep it...

Hey @wottpal, thanks for reviewing!

I was thinking on the "product" side before, because if there's some changes on the UI from the last version then devs would be confused/less interested with using ink!athon (and personally I like the stylings, I've already associated the look of the site with ink!athon).

But I agree the DX side is more important, so your ideas make sense. Just to confirm, what I need to is:
- [ ] Remove unnecessary styles (keep it as simple as possible)
- [ ] Keep only shadcn-ui components in `src/components/ui`

Is there something else to add?

**Comment by wottpal** [comment]
Exactly, 

- [ ] Remove unnecessary styles (i.e. re-sync/create components with shadcn CLI)
- [ ] Rebuild UI with shadcn/ui native components (cards, dropdowns, form, input, etc.)
- [ ] Try to use as few custom colors (e.g. `bg-purple-*`) but more the shadcn/tailwind-defined ones (e.g. `bg-primary`, `text-foreground`)

**Comment by wottpal** [comment]
@ical10 Looks way better already. Is it ready for review again?

**Comment by ical10** [comment]
@wottpal Yes, please review it again.

**Pull request merged**
